### ISSUE TITLE
How to list ALL

### ISSUE THREAD

**Issue by maka-io** [MrRaindrop/tree-cli#11]
It looks like you must specify the folder depth, any way to list all sub directories?

**Comment by yangshun** [comment]
@maka-io Check out this [tree-node-cli](https://github.com/yangshun/tree-node-cli) package that may do just what you need.

**Comment by MrRaindrop** [comment]
If you want list all sub directories, just type a big number for the -l parameter, like `tree -l 1024`. I think it's not a good idea to list all sub directories by default when 'l' is omitted, because sometimes the list would be so long that the shell term can't print the whole list but a part of it. Or if you have any good idea you can leave a comment here~
