### ISSUE TITLE
Stringify output

### ISSUE THREAD

**Issue by chancancode** [MrRaindrop/tree-cli#15]
Hello! Can you consider exporting the `stringify` function, or have some other wayto obtain the stringified output without having to shell out?  e.g. accepting a buffer or stream to write into.

I am using this as a library (i.e. `require`-ing it) and am mainly interested in getting the string output, not the data structure itself.

**Comment by MrRaindrop** [comment]
If your concern is the result would be too long for a string to handle, then there's no way to handle this situation properly, since this tool is based on the concatenation of strings. There's no way to output a stream without storing a long string of scanned report first.

Otherwise, the processing of file node should be changed to a stream way.

For now, I can only put the output string in the resolved result with the  data structure as well, and the stream or buffer can be generated from the ouput string.

**Comment by chancancode** [comment]
Hi! I don’t think I was worried about performance, the streaming nature was not important to the feature request.

I think the problem I ran into was that the library write directly to the console, so if I want to capture the formatted string for use inside javascript code, I need to run this as a child process and capture its standard output.

That seemed unnecessary, since the code is fully capable of just doing the work of collecting the files/directories and doing the formatting in memory and returning a string, instead of printing things directly to the console.

**Comment by MrRaindrop** [comment]
> Hi! I don’t think I was worried about performance...

I see, I've fixed this and exported a new data structure in the resolved result with a `report` string, which might be what your want. Just get it with:

```javascript
require('tree-cli')('your/root/path', ({ report, data }) => {
 getTheReport(report);
});
```

Pls check out the latest version 6.0.2.

**Comment by chancancode** [comment]
Thank you! I’ll give it a try!

**Comment by MrRaindrop** [comment]
@chancancode Sorry, my bad for the callback style example, actually it only support the promise way. I've changed the example above, pls check it out.
